### ISSUE TITLE
Can you add a Jupyter notebook with the example code?

### ISSUE THREAD

**Issue by Emasoft** [ishu121992/JupyterPilot#2]
I cannot reproduce the code of the example you wrote in the readme. It runs all steps fine, but no cell is created at the end with the source code.
Can you add a Jypiter notebook with the example code? So I can check if I'm doing something wrong.
Thanks!

**Comment by ishu121992** [comment]
Sure @Emasoft

**Comment by ishu121992** [comment]
https://www.youtube.com/watch?v=oQZ2rcxRaiw

@Emasoft please see this demo I created. Like Chatgpt, these models are not consistent with their response. So, they will not always result in same code.

**Comment by Emasoft** [comment]
Thanks, I've seen it. Three things:
1 - I still suggest you to add a notebook file (.ipynb) to the github repo as a demo. Copying code from a video is not the best.
2 - I suggest you to censor the API key in the video, or you could be banned if someone uses it to abuse the OpenAI service. Even in the notebook you should leave a ```<YOUR API KEY>``` placeholder in the code instead of a real API key.
3 - I don't know much about GPT models, but doesn't temperature=0 ensure that only one solution, the most probably correct, is choosen? Other values of temperature allow a certain randomness, and are only good for creative tasks, not coding. So I thought that with that set to zero the answers should be pretty consistent. I’m wrong?

**Comment by ishu121992** [comment]
1. I will add it today. 
2. Yes, I am actually going to delete it, which basically gives the same result. 
3. In tomorrow's update, I will set make all params including temp adjustable during initial codetocell call. Among all publicly available code synthesis models, this is probably the better one. The thing with temp is weird in this case. The models add some rubbish text in the output. Because of the drop in accuracy I went for 0 temp. Originally I wanted to create a node like editor with people creating code blocks using prompts and then combining the blocks to create a full fledge project. Due to consistency issues, I dropped the idea.
